name: 'File Size'
description: 'Record the file size in git notes'
inputs:
  file:
    description: 'File of which to compute the size'
    required: true
  save:
    description: 'Save'
    required: true
    default: true
outputs:
  size:
    description: "File size"
    value: ${{ steps.run-script.outputs.size }}
runs:
  using: "composite"
  steps:
    - run: echo "hello, world!"
      shell: bash
    - id: run-script
      run: ${{ github.action_path }}/test.sh
      shell: bash
      env:
        INPUT_FILE: ${{ inputs.file }}
        INPUT_SAVE: ${{ inputs.save }}
